---
- name: Deploy with Docker Compose
  hosts: local
  become: true

  tasks:
    - name: Stop and remove old containers and volumes
      command: docker-compose -f docker-compose.yml down -v
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') | default('/var/lib/jenkins/workspace/Retina') }}"

    - name: Rebuild Docker images without cache
      command: docker-compose -f docker-compose.yml build --no-cache
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') | default('/var/lib/jenkins/workspace/Retina') }}"

    - name: Start fresh containers
      command: docker-compose -f docker-compose.yml up -d
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') | default('/var/lib/jenkins/workspace/Retina') }}"
