---
- name: Deploy with Docker Compose
  hosts: local
  become: true

  tasks:
    - name: Run docker-compose up directly from workspace
      command: docker-compose -f docker-compose.yml up -d
      args:
        chdir: "{{ lookup('env', 'WORKSPACE') | default('/var/lib/jenkins/workspace/Retina') }}"
