---
- name: Deploy services to Minikube
  hosts: localhost
  become: false
  vars:
    kube_config: "{{ lookup('env', 'KUBECONFIG') | default('~/.kube/config', true) }}"
  tasks:

    - name: Set KUBECONFIG environment variable
      ansible.builtin.set_env:
        KUBECONFIG: "{{ kube_config }}"

    - name: Check Kubernetes access
      shell: |
        kubectl version --client
        kubectl get nodes
      register: kube_output
      ignore_errors: yes

    - name: Show Kubernetes output
      debug:
        var: kube_output.stdout_lines

    - name: Apply all Kubernetes YAML files
      shell: kubectl apply -f ./k8s
      args:
        chdir: "{{ playbook_dir }}"
