---
- name: Deploy to Kubernetes with Minikube
  hosts: local
  become: false  # Do not use root to avoid driver issues

  vars:
    workspace_dir: "{{ lookup('env', 'WORKSPACE') | default('/var/lib/jenkins/workspace/retina') }}"
    kube_dir: "{{ workspace_dir }}/.kube"
    minikube_dir: "{{ workspace_dir }}/.minikube"

  tasks:
    - name: Delete Minikube cluster if exists
      command: minikube delete
      ignore_errors: true

    - name: Create ~/.kube and ~/.minikube directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ kube_dir }}"
        - "{{ minikube_dir }}"

    - name: Start Minikube using Docker driver
      command: >
        minikube start
        --driver=docker
        --force
        --install-addons=true
        --delete-on-failure
      environment:
        MINIKUBE_HOME: "{{ workspace_dir }}"
        KUBECONFIG: "{{ kube_dir }}/config"

    - name: Apply Kubernetes manifests from local k8s/ folder
      command: kubectl apply -f k8s/
      args:
        chdir: "{{ workspace_dir }}"
      environment:
        MINIKUBE_HOME: "{{ workspace_dir }}"
        KUBECONFIG: "{{ kube_dir }}/config"
