apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prediction
  template:
    metadata:
      labels:
        app: prediction
    spec:
      volumes:
        - name: prediction-logs
          emptyDir: {}
      containers:
        - name: prediction
          image: pavan020504/prediction-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: prediction-logs
              mountPath: /var/log/app
