apiVersion: v1
kind: PersistentVolume
metadata:
  name: upload-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/data/uploads  # Path inside Minikube VM
  volumeMode: Filesystem
  nodeAffinity:  # This ensures that the PV is only scheduled on the correct node
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube  # Minikube node hostname; adjust if necessary
