apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: upload-volume
          persistentVolumeClaim:
            claimName: upload-pvc
        - name: web-logs
          emptyDir: {}  # New volume for logs
      containers:
        - name: web
          image: pavan020504/web-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: web-config
          volumeMounts:
            - name: upload-volume
              mountPath: /app/static/uploads
            - name: web-logs
              mountPath: /var/log/app  # Web app logs here
